name: fissa-example-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.5
  - numpy==1.21.0
  - scipy==1.7.0
  - pip=21.1.2
  - six==1.16.0
  - holoviews==1.13.2
  - pip:
    - bokeh==2.3.2
    - fissa[plotting]
    - future==0.18.2
    - h5py==3.3.0
    - imageio==2.9.0
    - numba==0.53.1
    - pandas==1.2.5
    - pillow==8.2.0
    - pyqt5==5.15.4
    - read-roi==1.6.0
    - scikit-image==0.18.1
    - scikit-learn==0.24.2
    - shapely==1.7.1
    - suite2p==0.10.0
    - tifffile==2021.6.14
